service: ticketera-api

plugins:
  - serverless-jetpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 30

functions:
  main:
    handler: src/lambda.handler
    environment:
      NODE_ENV: production
    events:
      - httpApi:
          method: ANY
          path: /{proxy+}